name: plantation
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  sqflite: ^2.2.2
  fluttertoast: ^8.1.2
  path: ^1.8.2
  customizable_counter: ^1.0.4
  image_picker: ^0.8.6
  signature: ^5.3.0
  permission_handler: ^8.2.0
  sizer: ^2.0.15
  path_provider: ^2.0.11
  intl: ^0.18.0
  shared_preferences: ^2.0.17
  geolocator: ^8.0.3
  flutter_launcher_icons: ^0.11.0
  flutter_rename_app_plus: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"

flutter_rename_app_plus:
  application_name: Plantation App
